building:
    stage: build
    script:
        - mvn -Dmaven.test.skip=true  clean install 
    only:
        refs:
            - merge_requests
unit_testing:
    stage : test
    script:
        - mvn test
    only:
        refs:
            - merge_requests
quality_testing:
    stage : test
    script:
        -  mvn checkstyle:check
    only:
        refs:
            - merge_requests
deployment:
    stage : deploy
    script:
        - mvn -Dmaven.test.skip=true  clean install 
        - mv  target/billing-1.war target/billing.war
        - sudo cp target/billing.war /opt/tomcat8085/webapps/
    only:
        refs:
            - merge_requests
        